import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { checkout } from "../lib/stripe/checkout";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Buy My Physical NFTs</h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Image
              alt="vintage tshirt"
              src="/images/teeone.png"
              width={400}
              height={400}
            />
            <p>Very expensive tshirt 1</p>
            <button
              onClick={() =>
                checkout({
                  lineItems: [
                    { price: "price_1L5jIfIA9blC304XwmlJyVLJ", quantity: 1 },
                  ],
                })
              }
            >
              BUY!
            </button>
          </div>
          <div className={styles.card}>
            <Image
              alt="old cassetes tshirt"
              src="/images/teetwo.png"
              width={400}
              height={400}
            />
            <p>Very expensive tshirt 2</p>
            <button
              onClick={() =>
                checkout({
                  lineItems: [
                    { price: "price_1L5jI8IA9blC304Xr9IB7MD0", quantity: 1 },
                  ],
                })
              }
            >
              BUY!
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}
